version: "3.8"

services:
  align:
    image: ohdejong/my-align-with-pdk:latest
    container_name: align
    volumes:
      - ./shared:/workspace
      - ./shared/pdks:/opt/pdk 
    working_dir: /workspace
    tty: true

  analog:
    image: ohdejong/analog-docker:latest
    container_name: analog
    volumes:
      - ./shared:/workspace
      - ./shared/pdks:/opt/pdk  
    environment:
      - DISPLAY=host.docker.internal:0.0
    working_dir: /workspace
    tty: true

  openlane:
    image: ohdejong/my-openlane-with-pdk:latest
    container_name: openlane
    volumes:
      - ./shared:/workspace
      - ./shared/pdks:/opt/pdk 
    working_dir: /workspace
    tty: true

  icarus:
    image: nchandra75/iverilog:latest
    container_name: icarus
    volumes:
      - ./shared:/workspace
    working_dir: /workspace
    tty: true
